name: Label Issue as In Progress

on:
  create:
    branches-ignore:
      - 'main'
      - 'master'
      - 'develop'

jobs:
  label-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Extract issue number from branch name
        run: |
          ISSUE_NUMBER=$(echo ${{ github.ref }} | sed 's|refs/heads/||' | grep -oE '^[0-9]+')
          echo "ISSUE_NUMBER=$ISSUE_NUMBER" >> $GITHUB_ENV

      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install -y gh

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Add "In Progress" label to the issue
        run: gh issue edit $ISSUE_NUMBER --add-label "In Progress"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}